FROM node:alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx

# WORKDIR /usr/share/nginx/html

# Remove the default nginx configuration

# RUN rm /opt/homebrew/etc/nginx/nginx.conf

# RUN rm -rf ./*

# Copy the custom nginx configuration that handles SPA routing

COPY --from=build /app/build /usr/share/nginx/html

RUN rm -f /etc/nginx/conf.d/default.conf
# RUN rm -f /opt/homebrew/etc/nginx/conf.d/default.conf

COPY  nginx.conf  /etc/nginx/conf.d/default.conf
# COPY  nginx.conf  /opt/homebrew/etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]