export const LOGIN_EXAMINER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_EXAMINER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_EXAMINER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_EXAMINER = 'LOGOUT_USER'
