export const LOGIN_SUPERVISOR_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_SUPERVISOR_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_SUPERVISOR_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_SUPERVISOR = "LOGOUT_USER";

export const LOGIN_STUDENT_BEGIN = "LOGIN_STUDENT_BEGIN";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";
