export const LOGIN_SUPERVISOR_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_SUPERVISOR_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_SUPERVISOR_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_SUPERVISOR = "LOGOUT_USER";

export const FETCH_EXAMS_SCHEDULE_BEGIN = "FETCH_EXAMS_SCHEDULE_BEGIN";
export const FETCH_EXAMS_SCHEDULE_SUCCESS = "FETCH_EXAMS_SCHEDULE_SUCCESS";
export const FETCH_EXAMS_SCHEDULE_ERROR = "FETCH_EXAMS_SCHEDULE_ERROR";
