name: CI

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Prepare production environment variables
              shell: bash
              env:
                  ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
                  REACT_APP_BACKEND_URL: http://localhost:3001
              run: |
                  echo "$ENV_PRODUCTION" > .env.production

            - name: Build the docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: false
                  tags: ghcr.io/cse-mosip/exam-attendance-ui:latest

            - name: Build and push the docker image to Github Container Registry
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/cse-mosip/exam-attendance-ui:latest
              if: github.ref == 'refs/heads/main'
